"""empty message

Revision ID: 5d9358d95804
Revises: 1c880abbd229
Create Date: 2020-07-26 23:34:59.990571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d9358d95804'
down_revision = '1c880abbd229'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teachers_goal',
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('goals_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['goals_id'], ['goals.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teachers_goal')
    # ### end Alembic commands ###
